source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'puma'

gem 'sqlite3'

gem 'sprockets-rails'

gem 'rails', '>= 7.1.3'
gem 'tailwindcss-rails', '~> 2.0'

group :test, :development do
  gem 'administrate'
  gem 'administrate_tailwind_theme', path: '../../'
  gem 'byebug'
  gem 'iso_country_codes', '~> 0.7.8'
end
